### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by apinner84** [archive-br-automation-com/mappView-File-Explorer#16]
Would it be possible to make this work with HTTPS?

If you run MappView with HTTPS enabled then the upload and download doesn't appear to work, presumably because the web service it creates is only HTTP?

**Comment by stephan1827** [comment]
I need to take a deeper look into this. I tried to change the web service to HTTPS, but that is not enough.

**Comment by apinner84** [comment]
I tried the same but just get a 404 on the upload.

I'll keep trying here and see if I can also make any progress.

**Comment by stephan1827** [comment]
I am sorry but I had no luck so far fixing this. I am not a JavaScript or HTML expert, so I am not sure what needs to be done to make this work.

**Comment by apinner84** [comment]
I made some progress. 

I've discovered that its not as simple as just replacing the AsHttp service with Https, you need both. You need to keep the Http service and then create additional Https services with the same settings. 

![image](https://user-images.githubusercontent.com/69159945/162941485-73d67a6c-50d9-4316-a9b0-dd15f880049a.png)

Obviously you need a certificate, key and ssl config as well.

I was able to access the upload form using https with the webserver set to HTTP + HTTPS

**Comment by stephan1827** [comment]
Sounds good, I will take another look at it next’s week

**Comment by stephan1827** [comment]
I am sorry but I tried the additional HTTPS service but it only works when I open the visualization on port 81. When I open it at as HTTPS it still does not show the upload button. Is there anything else you did to make this work?
